require 'bundler'
Bundler.require

desc 'Build the script to game/sottolio.js'
task :build do
  env = Opal::Environment.new
  env.append_path 'opal'

  File.open('../game/sottolio.js', 'w+') do |out|
    out << env['application'].to_s
  end
end